# PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0f4b1e58837abd1ab
  storageClassName: standard
#  awsElasticBlockStore:
#    volumeID: vol-0f4b1e58837abd1ab
    fsType: ext4

# PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  
# Deployment 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      volumes:
      - name: my-pvc-volume
        persistentVolumeClaim:
         claimName: my-pvc
      containers:
      - name: my-springboot-app
        image: 224779572000.dkr.ecr.ap-south-1.amazonaws.com/repo_4_task:latest
        imagePullPolicy: Always
        volumeMounts:
            - name: my-pvc-volume
              mountPath: /tmp/my-pvc-volume
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP



          
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
